const OPEN_ADD_CITY = 'OPEN_ADD_CITY';
const ADD_CITY_BEGIN = 'ADD_CITY_BEGIN';
const ADD_CITY_ERROR = 'ADD_CITY_ERROR';
const ADD_CITY_SUCCESS = 'ADD_CITY_SUCCESS';
const SAVE_CITY = 'SAVE_CITY';
const ADD_CITY_CLOSE = 'ADD_CITY_CLOSE';
const REMOVE_CITY = 'REMOVE_CITY';

export default {
	OPEN_ADD_CITY,
	ADD_CITY_BEGIN,
	ADD_CITY_ERROR,
	ADD_CITY_SUCCESS,
	SAVE_CITY,
	ADD_CITY_CLOSE,
	REMOVE_CITY,
};
