version: 2
jobs:
 build:
  docker:
   # specify the version you desire here
   - image: cimg/node:15.9.0

  working_directory: ~/repo

  environment:
   # Customize the JVM maximum heap limit
   JVM_OPTS: -Xmx3200m
   TERM: dumb

  steps:
   - checkout

   - run:
      name: Login to DockerHub
      command: echo "$DOCKER_TOKEN" | docker login -u $DOCKER_USER --password-stdin

   # Download and cache dependencies
   - restore_cache:
      keys:
       - v1-dependencies-{{ checksum "yarn.lock" }}
       # fallback to using the latest cache if no exact match is found
       - v1-dependencies-

   - run: echo "REACT_APP_OPENWEATHERMAP_API_KEY=$OWM_API_KEY" > .env.production

   - run: echo "REACT_APP_OPENWEATHERMAP_API_KEY=$OWM_API_KEY" > .env

   - run: yarn install --frozen-lockfile

   - run: yarn run build

   - save_cache:
      paths:
       - ~/node_modules
      key: v1-dependencies-{{ checksum "yarn.lock" }}

   # run tests!
   - run:
      name: Checking Tests
      command: yarn run test

   - setup_remote_docker:
      version: 19.03.13

   - run:
      name: Build Docker Image
      command: docker build -t open1904/$HEROKU_APP-app .

   - run:
      name: Push Docker Image to DockerHub
      command: docker push open1904/$HEROKU_APP-app:latest

   - run:
      name: Setup Heroku
      command: bash .circleci/setup-heroku.sh

   - run:
      name: Push to Heroku
      command: |
       heroku git:clone -a $HEROKU_APP
       rm -rf $HEROKU_APP/build
       cp -R build $HEROKU_APP/build
       cd $HEROKU_APP
       git config --global user.email $HEROKU_LOGIN
       git config --global user.name $HEROKU_LOGIN
       git add .
       git commit -m "update frontend"
       git push heroku master

   - store_artifacts:
      path: build
      destination: artifacts
