const FETCH_WEATHER_BEGIN = 'FETCH_WEATHER_BEGIN';
const FETCH_WEATHER_ERROR = 'FETCH_WEATHER_ERROR';
const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';

export default {
	FETCH_WEATHER_BEGIN,
	FETCH_WEATHER_ERROR,
	FETCH_WEATHER_SUCCESS,
};
